admin_web_sensor_index:
  path: /admin/sensor
  methods: [ GET ]
  controller: App\UI\Web\Controller\SensorManagement\SensorManagementController::index

admin_web_sensor_show:
  path: /admin/sensor/show/{id<\d+>}
  methods: [ GET ]
  controller: App\UI\Web\Controller\SensorManagement\SensorManagementController::show
